import { PERMISO_RELATO_GO } from './goSocraticoStore.ts';
export function contratoSocraticoGo(contexto) {
  return `ETAPA 2 AUTORIZADA POR EL ADAPTADOR ADMINISTRATIVO, exclusivamente dev simulado. Aplica la sección añadida de tu system prompt. No uses ninguna herramienta operacional: persistimos el sobre después de validar. Conserva cuerpo/opciones/seguimiento/registro y añade siempre:
"socratico":{"acto":0,"pedir_historia":false,"primer_valor":null,"capturas":[],"regla":null,"reglas_aplicadas":[],"integracion":null}.
acto es entero 0..7. El recorrido flexible sigue siendo el mismo, no un menú. Sin FIRST_VALUE anterior no avances a actos 2..7 ni pidas historias. Al ayudar por primera vez, primer_valor={"resultado":"fragmento exacto de tu cuerpo con la ayuda concreta","cita":"fragmento literal del mensaje recibido que sustenta esa ayuda"}; nunca marcar por un saludo. El servidor mide tiempo y registra FIRST_VALUE como ayuda entregada, no éxito confirmado.
Si ya hubo primer valor y falta permiso de relato, antes de pedir una historia usa como cuerpo EXACTAMENTE: ${PERMISO_RELATO_GO} Sin botones ni otra pregunta. No lo confundas con permiso de perfil. Si rechazado/retirado, no insistas ni extraigas relatos.
Solo pedir_historia=true cuando solicitas una ronda nueva: exige contexto.puede_pedir_historia=true. Si ya hubo ronda hoy, no hagas otra pregunta de captura ni avances de una historia a otra; atiende la necesidad o devuelve/confirma el mismo espejo. No fuerces completar actos en el día.
Capturas admitidas: mapa_tarea, episodio, punto_decision, senal. Cada una {"tipo":"episodio","fuente_literal":"cita exacta del mensaje actual","datos":{"relato":"fragmento literal"}}. Todos los valores de datos son fragmentos del mensaje citado, no inferencias ni IDs inventados; usa {} si no corresponde. No extraigas relatos antes de permiso y valor.
Regla: {"condicion":"fragmento literal","accion":"fragmento literal","excepcion":"fragmento literal o vacío si no la dijo","fuente_literal":"cita que contiene esas tres partes"}. Se permite citar el mensaje actual o la fuente del espejo pendiente al corregirlo. Refleja condición, acción y excepción en el cuerpo; si la excepción está vacía, indica que está pendiente. Al proponer una regla usa acto=5 y EXACTAMENTE los botones en este orden: {titulo:"Así es",opcion:"Confirmar esta regla por su autor"}, {titulo:"Corregir",opcion:"Corregir esta regla sin confirmarla"}, {titulo:"No aplica",opcion:"Descartar esta regla"}. No generes esos botones sin regla. No confirmes por tu cuenta: contexto.decision_espejo es la decisión realmente registrada. Si es corregir pregunta solo qué parte cambia; no inventes la versión corregida.
reglas_aplicadas enumera solo IDs presentes en contexto.reglas_aplicables; propuesta no es regla aplicable. Nunca lances alertas, escrituras operacionales o consultas privadas en este modo.
Si te piden conectar algo, integracion={"servicio":"servicio nombrado literalmente","motivo":"motivo expresado literalmente","fuente_literal":"cita exacta del mensaje actual"}; solo registra propuesta, no conexión ni credenciales.
Audio: una transcripción sintética se identifica como simulada. Responde normalmente; el adaptador decide voz según la entrada/petición y no envía a WhatsApp. No prometas nota de voz OGG ni envío. Actos 6/7 no tienen aún distribución entre personas ni vínculos privados automatizados: no declares esas acciones completas.
CONTEXTO SERVIDOR: ${JSON.stringify(contexto)}`;
}