import { ArrowRight, LockKeyhole, ShieldAlert } from 'lucide-react';
import { Image } from '@/components/ui/image';
import PolpaicoSection from '@/components/polpaico/PolpaicoSection';
import PolpaicoMetrics from '@/components/polpaico/PolpaicoMetrics';
import PolpaicoStatus from '@/components/polpaico/PolpaicoStatus';
const usd = value => `USD $${Number(value || 0).toLocaleString('es-CL')}`;
export default function CalidadPolpaico({ data }) {
  const { ncs, partidas, edps, kpis: k } = data;
  const evidencia = ncs.find(n => n.gravedad === 'critica' && n.evidencia_foto_url);
  const pagos = nc => edps.filter(e => e.partida_id === nc.partida_id && e.estado === 'bloqueado_calidad');
  return <PolpaicoSection id="calidad" number="03" eyebrow="Blindaje de margen" title="Trazabilidad de Calidad — No Quality, No Pay" subtitle="Cada NC crítica bloquea el pago automáticamente. El hormigón no se paga sin calidad verificada.">
    <PolpaicoMetrics items={[{ label: 'NCs abiertas', value: k.nc_abiertas, tone: 'text-danger' }, { label: 'EDPs bloqueados', value: k.edps_bloqueados, tone: 'text-danger' }, { label: 'USD retenidos', value: usd(k.monto_retenido), tone: 'text-warn' }]} />
    <div className="grid lg:grid-cols-3 gap-5 mb-5"><div className="lg:col-span-2 bg-card rounded-lg border border-border p-5 sm:p-6"><h3 className="flex items-center gap-2 font-semibold mb-5"><LockKeyhole className="w-4 h-4 text-danger" />Cadena de trazabilidad</h3>
      {ncs.map(n => <div key={n.id} className="flex flex-col sm:flex-row sm:items-center gap-3 mb-4 text-sm"><div className="border border-danger/50 bg-danger/10 rounded-lg p-4 flex-1"><ShieldAlert className="w-4 h-4 text-danger mb-2" /><strong>{n.numero_correlativo}</strong><p className="text-xs text-muted-foreground mt-1">{n.estado} · {n.gravedad}</p></div><ArrowRight className="w-4 h-4 text-muted-foreground shrink-0 rotate-90 sm:rotate-0" /><div className="border border-border rounded-lg p-4 flex-1"><strong>{partidas.find(p => p.id === n.partida_id)?.codigo || 'Partida'}</strong><p className="text-xs text-muted-foreground mt-1">{partidas.find(p => p.id === n.partida_id)?.nombre}</p></div><ArrowRight className="w-4 h-4 text-muted-foreground shrink-0 rotate-90 sm:rotate-0" /><div className="border border-warn/40 bg-warn/5 rounded-lg p-4 flex-1">{pagos(n).map(e => <p key={e.id} className="text-xs mb-1"><strong>{e.numero_edp}</strong><span className="block text-warn mt-1">{usd(e.monto_usd)} · bloqueado</span></p>)}{!pagos(n).length && <span className="text-muted-foreground">Sin EDP bloqueado</span>}</div></div>)}
      {!ncs.length && <p className="text-muted-foreground">No hay no conformidades registradas.</p>}
      <p className="text-xs text-muted-foreground mt-4">La resistencia del sensor no sustituye el cierre documentado de una no conformidad.</p>
    </div>{evidencia && <figure className="bg-card border border-border rounded-lg overflow-hidden"><Image src={evidencia.evidencia_foto_url} alt="Imagen ilustrativa de trabajo industrial para la NC del piloto" loading="lazy" className="w-full h-48" /><figcaption className="p-4 text-xs text-muted-foreground leading-relaxed">Evidencia de muestra · imagen ilustrativa<br />GPS simulado: {evidencia.coordenadas_gps}</figcaption></figure>}</div>
    <div className="overflow-x-auto bg-card border border-border rounded"><table className="w-full text-sm"><caption className="sr-only">No conformidades y pagos afectados</caption><thead><tr>{['Correlativo', 'Descripción', 'Gravedad', 'Estado', 'Partida', 'EDP afectado', 'Monto retenido'].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{ncs.map(n => <tr key={n.id}><td className="font-mono whitespace-nowrap">{n.numero_correlativo}</td><td className="min-w-64">{n.descripcion}</td><td><PolpaicoStatus value={n.gravedad} /></td><td>{n.estado}</td><td className="whitespace-nowrap">{partidas.find(p => p.id === n.partida_id)?.codigo}</td><td className="whitespace-nowrap">{pagos(n).map(e => e.numero_edp).join(', ') || '—'}</td><td className="text-warn whitespace-nowrap">{usd(pagos(n).reduce((s, e) => s + (e.monto_usd || 0), 0))}</td></tr>)}{!ncs.length && <tr><td colSpan={7}>Sin NCs registradas.</td></tr>}</tbody></table></div>
  </PolpaicoSection>;
}