import { Radio, MessageCircle, Database, Network, ShieldCheck } from 'lucide-react';
import PolpaicoSection from '@/components/polpaico/PolpaicoSection';
const conectores = [[MessageCircle, 'WhatsApp Business', 'Simulado · no conectado'], [Radio, 'ObraLink API', 'Lecturas simuladas'], [Network, 'ERP MCP · Cerro Blanco', 'Simulado'], [Database, 'Pinecone + Neo4j', 'Configurados · no verificados']];
export default function ComandoPolpaico({ data }) {
  const pendiente = data.alertas.find(a => a.tipo === 'resistencia_alcanzada' && ['activa', 'reconocida'].includes(a.estado));
  return <PolpaicoSection id="comando" number="06" eyebrow="Gobernanza y operación" title="Centro de Comando — Polpaico OS" subtitle="Estado de conectores y gobernanza HITL. Las fuentes externas de este piloto no están operando en vivo.">
    <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{conectores.map(([Icon, titulo, estado]) => <div key={titulo} className="bg-card border border-border rounded-lg p-5"><Icon className="w-5 h-5 text-muted-foreground mb-5" /><h3 className="text-sm font-semibold">{titulo}</h3><p className="text-xs text-warn mt-3 flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-warn shrink-0" />{estado}</p><p className="font-mono text-[10px] text-muted-foreground mt-2">LATENCIA: NO MEDIDA</p></div>)}</div>
    <div className="grid lg:grid-cols-2 gap-5 mt-5"><div className="border border-primary bg-secondary/15 rounded-lg p-6"><div className="flex gap-3 items-center mb-4"><ShieldCheck className="w-5 h-5 text-ok" /><h3 className="font-semibold">Supervisión humana · HITL</h3></div><p className="text-xs text-warn uppercase tracking-widest mb-3">{pendiente ? 'Pendiente de evaluación' : 'Sin alertas de resistencia pendientes'}</p><p className="text-sm leading-relaxed">{pendiente?.titulo || 'No hay una aprobación de desencofrado registrada en este portal.'}</p><p className="text-xs text-muted-foreground mt-4 leading-relaxed">Acceso público de solo lectura. No se atribuyen aprobaciones a personas sin un registro verificable; alcanzar f’c no autoriza automáticamente el desencofrado ni libera pagos.</p></div>
      <div className="bg-card border border-border rounded-lg p-6"><div className="flex flex-wrap justify-between gap-2 mb-5"><h3 className="font-semibold">Créditos cognitivos</h3><span className="text-xs text-muted-foreground">Septiembre 2026 · simulado</span></div><p className="text-3xl font-semibold tabular-nums">49.680 <span className="text-sm font-normal text-muted-foreground">/ 80.000 CPO</span></p><div role="progressbar" aria-label="Consumo simulado de CPO" aria-valuemin={0} aria-valuemax={80000} aria-valuenow={49680} className="h-2.5 rounded-full bg-muted overflow-hidden mt-5"><div className="h-full bg-ok rounded-full" style={{ width: '62.1%' }} /></div><p className="text-sm text-muted-foreground mt-5">Margen de inferencia: <span className="text-ok">27,3%</span></p><p className="text-[10px] text-muted-foreground mt-2">Cifras de demostración; no representan facturación ni consumo medido.</p></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-7">{[['EBITDA 2025', 'MM$37.768'], ['Período cobro', '50 días'], ['Período pago', '60 días'], ['TSR Coactiva', '12% → meta 28%']].map(([label, value]) => <div key={label} className="border-l-2 border-primary pl-4"><p className="text-xs text-muted-foreground">{label}</p><p className="text-lg font-semibold mt-2">{value}</p></div>)}</div><p className="text-[10px] text-muted-foreground mt-4">Referencias corporativas estáticas suministradas para el piloto; no auditadas por GO.</p>
  </PolpaicoSection>;
}