import { useRef, useState } from 'react';
import { ArrowUp, Paperclip, Loader2, X } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import VoiceRecorder from '@/components/agent/VoiceRecorder';
export default function PolpaicoComposer({ onSend, busy }) {
  const [text,setText]=useState(''), [files,setFiles]=useState([]), [uploading,setUploading]=useState(false), [error,setError]=useState('');
  const input=useRef(null);
  const upload=async e=>{ const selected=Array.from(e.target.files||[]); e.target.value=''; if(!selected.length)return; setUploading(true); setError(''); try { const rows=await Promise.all(selected.map(async f=>{const {file_uri}=await base44.integrations.Core.UploadPrivateFile({file:f});return {name:f.name,file_uri};})); setFiles(prev=>[...prev,...rows]); } catch(err){setError('No se pudo adjuntar el archivo. Intenta nuevamente.');} finally{setUploading(false);} };
  const send=async()=>{if(busy||uploading||(!text.trim()&&!files.length))return;setUploading(true);setError('');try{const urls=await Promise.all(files.map(async f=>(await base44.integrations.Core.CreateFileSignedUrl({file_uri:f.file_uri,expires_in:3600})).signed_url));const ok=await onSend(text.trim()||'Analiza este adjunto para entender el proceso, detectar oportunidades y proponer el siguiente paso. Distingue hechos del documento e hipótesis; no lo registres como evidencia verificada ni lo asignes al piloto por defecto.',urls);if(ok){setText('');setFiles([]);}}catch(err){setError('No se pudo preparar el envío. Tus adjuntos se conservan; vuelve a intentarlo.');}finally{setUploading(false);} };
  return <div className="shrink-0 p-3 sm:p-5 border-t border-border bg-background"><div className="max-w-3xl mx-auto rounded-2xl border border-border bg-card p-3"><div className="flex flex-wrap gap-2">{files.map(f=><span key={f.file_uri} className="text-xs bg-muted p-2 rounded flex items-center gap-2">{f.name}<button aria-label={`Quitar ${f.name}`} onClick={()=>setFiles(v=>v.filter(x=>x.file_uri!==f.file_uri))}><X className="w-3.5 h-3.5" /></button></span>)}</div><textarea aria-label="Mensaje a GO Polpaico" rows={2} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}} placeholder="Cuéntame qué necesita tu equipo, exploremos un proceso o revisemos el piloto…" className="w-full bg-transparent resize-none text-sm leading-relaxed outline-none py-2 min-h-16 max-h-36 placeholder:text-muted-foreground" /><div className="flex items-center gap-2"><VoiceRecorder disabled={busy||uploading} onPartial={setText} onTranscript={setText} /><input type="file" accept=".pdf,.png,.jpg,.jpeg,.csv,.xlsx,.txt" multiple ref={input} onChange={upload} className="hidden" /><button aria-label="Adjuntar documento" disabled={busy||uploading} onClick={()=>input.current?.click()} className="w-11 h-11 flex items-center justify-center text-muted-foreground disabled:opacity-40">{uploading?<Loader2 className="w-4 h-4 animate-spin" />:<Paperclip className="w-4 h-4" />}</button><span className="hidden sm:block text-[10px] text-muted-foreground">Revisa el dictado antes de enviarlo</span><button onClick={send} aria-label="Enviar mensaje" disabled={busy||uploading||(!text.trim()&&!files.length)} className="ml-auto h-11 w-11 rounded-xl bg-primary text-primary-foreground flex items-center justify-center disabled:opacity-40">{busy?<Loader2 className="w-4 h-4 animate-spin" />:<ArrowUp className="w-5 h-5" />}</button></div></div>{error&&<p role="alert" className="text-xs text-danger mt-2">{error}</p>}<p className="text-center text-[10px] text-muted-foreground mt-2">GO · Polpaico OS — no sustituye la aprobación del profesional responsable.</p></div>;
}