import { ArrowUpRight, Radio, ShieldAlert, Truck, Leaf, RefreshCw } from 'lucide-react';
const titulos={resumen:'Panorama del piloto',logistica:'Despachos',telemetria:'Resistencia',calidad:'Calidad y pagos',esg:'Impacto ESG',informe:'Informe ejecutivo',comando:'Gobernanza HITL'};
export default function PolpaicoContext({data,view,onAsk,onExpand,refreshing,onRefresh}) {
  if(!data)return <div className="p-5 text-sm text-muted-foreground">Cargando registros del piloto…</div>;
  const k=data.kpis, p=data.proyecto;
  const ask=view==='esg'?'Prepara un borrador ESG para P-POL-002 con espesor 0.15 m. Muéstrame los datos antes de guardarlo.':view==='logistica'?'Quiero registrar un despacho manual en el piloto. Pídeme los datos necesarios.':view==='telemetria'?'Quiero registrar una lectura simulada. Pídeme partida, resistencia, temperatura y hora.':view==='comando'?'Prepara una solicitud de revisión humana para P-POL-001 por la NC crítica abierta.':view==='informe'?'Exporta el último informe ejecutivo del piloto a PDF.':'Explica la cadena NC → partida → EDP y el siguiente paso para resolverla.';
  return <div className="p-4 space-y-5"><div className="flex justify-between items-start gap-2"><div><p className="uppercase text-[9px] text-ok tracking-widest">Contexto de GO</p><h2 className="font-semibold mt-2">{titulos[view]}</h2><p className="text-[10px] text-muted-foreground mt-1">Icafal Colina · datos simulados</p></div><button aria-label="Actualizar registros" onClick={onRefresh} disabled={refreshing} className="p-2 text-muted-foreground"><RefreshCw className={`w-3.5 h-3.5 ${refreshing?'animate-spin':''}`} /></button></div>
    <div className="grid grid-cols-2 gap-2">{[['Avance',`${p.avance_real}%`],['Retenido',`$${k.monto_retenido.toLocaleString('es-CL')}`]].map(([l,v])=><div className="bg-card border border-border p-3 rounded-lg" key={l}><p className="text-[10px] text-muted-foreground">{l}{l==='Retenido'?' · USD':''}</p><p className="text-xl font-semibold mt-2">{v}</p></div>)}</div>
    {['resumen','calidad','informe','comando'].includes(view)&&<div className="rounded-lg border border-danger/30 bg-danger/5 p-4"><ShieldAlert className="w-4 h-4 text-danger mb-3"/><p className="text-sm font-semibold">{k.nc_criticas} NC crítica · {k.edps_bloqueados} EDP bloqueado</p>{data.ncs.filter(n=>!['cerrada','aprobada'].includes(n.estado)).map(n=><div key={n.id} className="text-xs mt-3"><p>{n.numero_correlativo}</p><p className="text-muted-foreground mt-1 leading-relaxed">{n.descripcion}</p><p className="text-warn mt-3">{data.partidas.find(p=>p.id===n.partida_id)?.codigo} → {data.edps.filter(e=>e.partida_id===n.partida_id&&e.estado==='bloqueado_calidad').map(e=>e.numero_edp).join(', ')}</p></div>)}</div>}
    {['resumen','telemetria'].includes(view)&&<div><p className="text-xs font-medium flex gap-2 items-center mb-3"><Radio className="w-3.5 h-3.5 text-ok"/>Resistencia del hormigón</p>{data.partidas.filter(p=>p.sensor_id).map(p=><button key={p.id} onClick={()=>onAsk(`Analiza ${p.codigo}: cruza sensor ${p.sensor_id}, calidad y pagos.`)} className="w-full text-left py-3 border-t border-border"><div className="flex justify-between text-xs gap-2"><span className="text-muted-foreground">{p.sensor_id}</span><strong className={p.mpa_lectura_actual>=p.mpa_especificado?'text-ok':'text-warn'}>{p.mpa_lectura_actual} / {p.mpa_especificado} MPa</strong></div><p className="text-[10px] text-muted-foreground mt-1">{p.codigo}</p></button>)}</div>}
    {view==='logistica'&&data.despachos.map(d=><div key={d.id} className="p-3 rounded-lg bg-card border border-border"><p className="text-xs flex items-center gap-2"><Truck className="w-4 h-4 text-ok"/>Guía {d.guia_despacho} · {d.volumen_m3} m³</p><p className="text-xs text-muted-foreground mt-2">{d.chofer_nombre} · {d.estado.replaceAll('_',' ')}</p>{d.audio_transcripcion&&<p className="text-xs mt-3 leading-relaxed">“{d.audio_transcripcion}”</p>}</div>)}
    {view==='esg'&&<div className="bg-secondary/20 border border-primary/40 p-4 rounded-lg"><Leaf className="w-5 h-5 text-ok mb-4"/><p className="text-2xl font-semibold text-ok">{k.arboles.toLocaleString('es-CL')}</p><p className="text-xs text-muted-foreground">árboles equivalentes estimados</p><p className="text-sm mt-4">{k.volumen_hormipurifica} m³ · {k.superficie} m² · {k.co2} kg CO₂</p><p className="text-[10px] text-muted-foreground mt-4">Factores preliminares. No acredita mitigación real.</p>{data.certificados.map(c=><p key={c.id} className="text-xs mt-4 break-words">{c.codigo_certificado} · {c.estado}</p>)}</div>}
    <button onClick={()=>onAsk(ask)} className="w-full min-h-11 text-left p-3 rounded-lg bg-primary/25 border border-primary/40 text-xs text-ok flex justify-between items-center gap-2">{view==='esg'?'Preparar borrador con GO':view==='logistica'?'Dictar nuevo despacho':view==='telemetria'?'Registrar lectura simulada':view==='comando'?'Solicitar revisión humana':view==='informe'?'Pedir PDF a GO':'Analizar con GO'}<ArrowUpRight className="w-4 h-4 shrink-0"/></button><button onClick={onExpand} className="w-full text-xs min-h-11 border border-border rounded-lg text-muted-foreground hover:text-foreground">Abrir detalle completo</button><p className="text-[9px] text-muted-foreground leading-relaxed">Actualización cada 30 s. WhatsApp requiere vinculación; ObraLink y ERP no están conectados.</p>
  </div>;
}